# Warm Start Testing

In [1]:
import numpy as np
import gurobipy as gp
import math
import sympy
import contextlib
import time
import os
from utils import result, METHODS, INF, EPS
from mps_reader_preprocessor import read_mps_preprocess
from polyhedral_model import PolyhedralModel
from polyhedron import Polyhedron

## Read in Polyhedron P

In [2]:
# problems = ['adlittle', 'afiro', 'agg2','agg3','agg', 'bandm',
#  'beaconfd', 'blend', 'bnl1', 'boeing1', 'boeing2', 'bore3d', 'brandy', 'capri',
#  'cre-c', 'cycle', 'degen2', 'degen3', 'e226', 'etamacro', 'fffff800', 'finnis',
#  'fit1d', 'fit1p', 'forplan', 'ganges', 'gfrd-pnc', 'grow15', 'grow22', 'grow7',
#  'israel', 'kb2', 'ken-07', 'lotfi', 'maros', 'modszk1', 'pds-02', 'perold',
#  'pilot4', 'pilotnov', 'qap08', 'recipe', 'sc105', 'sc205', 'sc50a',
#  'sc50b', 'scagr25', 'scagr7', 'scfxm1', 'scfxm2', 'scfxm3', 'scorpion', 'scrs8',
#  'scsd1', 'scsd6', 'scsd8', 'sctap1', 'sctap2', 'sctap3', 'seba', 'share1b',
#  'share2b', 'shell', 'ship04l', 'ship04s', 'ship08l', 'ship08s', 'ship12l', 'ship12s',
#  'sierra', 'stair', 'standata', 'standgub', 'standmps', 'stocfor1', 'stocfor2', 'tuff',
#  'vtp_base', 'wood1p']


# # mps_fn='C:\Users\DillW\OneDrive - The University of Colorado Denver\Documents\GitHub\simplex_like_alg\netlib_lp_subset\kb2'
# for i in problems:
#     problem_dir = 'netlib_lp_subset'
#     # problem = 'afiro'
#     mps_fn=os.path.join(problem_dir, i)
#     results_dir='results'
#     max_time=300
#     sd_method='dual_simplex'
#     reset=False,
#     partition_polytope=False
#     n=0
#     k=0
#     spindle=False
#     spindle_dim=0
#     n_cone_facets=0
#     n_parallel_facets=0

#     ### Build Initial Polyhedron from file
#     print(f'Reading {mps_fn}...')
#     c, B, d, A, b = read_mps_preprocess(mps_fn)
#     print('Building polyhedron...')
#     P = Polyhedron(B, d, A, b, c)

In [3]:
problem_dir = 'netlib_lp_subset'
# problem = 'kb2'
# problem = 'adlittle'
# problem = 'angela_test_prob'
problem = 'network_ex'
# problem = 'gfrd-pnc'
mps_fn=os.path.join(problem_dir, problem)
results_dir='results'
max_time=300
sd_method='dual_simplex'
reset=False,
partition_polytope=False
n=0
k=0
spindle=False
spindle_dim=0
n_cone_facets=0
n_parallel_facets=0

## Perform SDCA

### Original Code

In [4]:
### Build Initial Polyhedron from file
print(f'Reading {mps_fn}...')
c, B, d, A, b = read_mps_preprocess(mps_fn)
print('Building polyhedron...')
P = Polyhedron(B, d, A, b, c)

Reading netlib_lp_subset\network_ex...
Building polyhedron...
Problem size: n = 5,  m_B = 10,  m_A = 4


In [5]:
print('Finding feasible solution...')
x_feasible = P.find_feasible_solution(verbose=False)

Finding feasible solution...
Set parameter Username
Academic license - for non-commercial use only - expires 2025-04-01


In [6]:
equality = np.all(np.isclose(np.dot(A, np.array(x_feasible)), b))
inequality = np.all(np.dot(B, np.array(x_feasible))<= d)
print(equality)
print(inequality)

True
True


In [7]:
x = x_feasible
c=None
verbose=False
method='dual_simplex'
reset=False
max_time=300
first_warm_start=None
save_first_steps=0
problem_name=''

In [8]:
if c is not None:
    P.set_objective(c)

t0 = time.time()
x_current = x
if save_first_steps:
    np.save('solutions/{}_0.npy'.format(problem_name), x_current)      
active_inds = P.get_active_constraints(x_current)
# print(len(active_inds))
    
pm = P.build_polyhedral_model(active_inds=active_inds, method=method)

if first_warm_start is not None:
    print('Using custom warm start')
    pm.set_solution(first_warm_start)
t1 = time.time()
build_time = t1 - t0
print('Polyhedral model build time: {}'.format(build_time))
    
sub_times = {'sd': [], 'step': [], 'solve': [], 'phase_times': []}    
descent_circuits = []
obj_values = []
step_sizes = []
iter_times = []
simplex_iters = []
iteration = 0
obj_value = P.c.dot(x_current)
obj_values.append(obj_value)
t2 = time.time()
iter_times.append(t2 - t1)


# compute steepest-descent direction
descent_direction, y_pos, y_neg, steepness, num_steps, solve_time, phase_times = pm.compute_sd_direction(verbose=verbose)
print(descent_direction)
simplex_iters.append(num_steps)
sub_times['solve'].append(solve_time)
sub_times['phase_times'].append(phase_times)
    
t3 = time.time()
sub_times['sd'].append(t3 - t2)
    
while abs(steepness) > EPS:
        
    t3 = time.time()
    if reset:
        pm.reset()
        
    # take maximal step
    x_current, alpha, active_inds = P.take_maximal_step(descent_direction, y_pos, y_neg)  
        
    if iteration % 50 == 0 or iteration == 1:
        print('\nIteration {}'.format(iteration))
        print('Objective: {}'.format(obj_value))
        print('Steepness: {}'.format(steepness))
        print('Step length: {}'.format(alpha))
        
    t4 = time.time()
    obj_value = P.c.dot(x_current)
    obj_values.append(obj_value)
    iter_times.append(t4 - t1)
    sub_times['step'].append(t4 - t3) 
    descent_circuits.append(descent_direction)
    step_sizes.append(alpha)     
                
    if math.isinf(alpha):
        # problem is unbounded
        result(status=1, circuits=descent_circuits, steps=step_sizes)
        
    # compute steepest-descent direction
    pm.set_active_inds(active_inds)
    descent_direction, y_pos, y_neg, steepness, num_steps, solve_time, phase_times = pm.compute_sd_direction(
                                                                                                verbose=verbose)
        
    t5 = time.time()
    sub_times['sd'].append(t5 - t4)
    sub_times['solve'].append(solve_time)
    sub_times['phase_times'].append(phase_times)
    simplex_iters.append(num_steps)
        
    iteration += 1
    current_time = t5 - t1
    if current_time > max_time:
        result(status=2)
    if iteration <= save_first_steps:
        np.save('solutions/{}_{}.npy'.format(problem_name, iteration), x_current)

t6 = time.time()
total_time = t6 - t1   
print('Total time for steepest-descent scheme: {}'.format(total_time))

Building polyhedral model. Solve method: dual_simplex
Set parameter Method to value 1
Polyhedral model built!
Polyhedral model build time: 0.002881288528442383
[ 0.125 -0.125  0.     0.125 -0.125]

Iteration 0
Objective: 25.0
Steepness: -0.125
Step length: 40.0
Total time for steepest-descent scheme: 0.006867408752441406


In [9]:
x_orig = x_current

In [10]:
obj_values[-1]

20.0

### Updated Code

In [11]:
### Build Initial Polyhedron from file
print(f'Reading {mps_fn}...')
c, B, d, A, b = read_mps_preprocess(mps_fn)
print('Building polyhedron...')
P = Polyhedron(B, d, A, b, c)

Reading netlib_lp_subset\network_ex...
Building polyhedron...
Problem size: n = 5,  m_B = 10,  m_A = 4


In [12]:
print('Finding feasible solution...')
x_feasible = P.find_feasible_solution(verbose=False)

Finding feasible solution...


In [13]:
eq_cont_sat = np.all(np.isclose(np.dot(A, np.array(x_feasible)),b))
ineq_cont_sat = np.all(np.dot(B, np.array(x_feasible)) <=d)
print(f'equality constraints satisfied by feaisble soln: {eq_cont_sat}')
print(f'inequality constraints satisfied by feaisble soln: {ineq_cont_sat}')

equality constraints satisfied by feaisble soln: True
inequality constraints satisfied by feaisble soln: True


In [14]:
x = x_feasible
c=None
verbose=False
method='dual_simplex'
reset=False
max_time=300
first_warm_start=None
save_first_steps=0
problem_name=''

In [15]:
if c is not None:
    P.set_objective(c)
 
t0 = time.time()
x_current = x
if save_first_steps:
    np.save('solutions/{}_0.npy'.format(problem_name), x_current)      
active_inds = P.get_active_constraints(x_current)
init_inds = active_inds
# print(active_inds)
    
pm = P.build_polyhedral_model(active_inds=active_inds, method=method)
# print(pm.x)

if first_warm_start is not None:
    print('Using custom warm start')
    pm.set_solution(first_warm_start)
t1 = time.time()
build_time = t1 - t0
print('Polyhedral model build time: {}'.format(build_time))
    
sub_times = {'sd': [], 'step': [], 'solve': [], 'phase_times': []}    
descent_circuits = []
obj_values = []
step_sizes = []
iter_times = []
simplex_iters = []
iteration = 0
obj_value = P.c.dot(x_current)
obj_values.append(obj_value)
t2 = time.time()
iter_times.append(t2 - t1)

####get edge for initial circuit direction here#########
x_feasible_2= P.second_vert(x_current, obj_value, verbose=False)
# print(x_feasible_2)
edge = np.array(x_feasible_2) - np.array(x_current)
B_edge = np.dot(B,np.array(edge))
norm = np.linalg.norm(np.array(B_edge),1)
normed_B_edge = B_edge/(norm)
init_y_pos = []
init_y_neg = []
for entry in normed_B_edge:
    if entry >= 0:
        init_y_pos.append(entry)
        init_y_neg.append(0)
    else:
        init_y_pos.append(0)
        init_y_neg.append(-entry)

# print(f'first vertex: {x_feasible}')
# print(f'second vertex: {x_feasible_2}')
# print(f'init edge: {init_edge}')
########################################################

# compute steepest-descent direction
descent_direction, y_pos, y_neg, steepness, num_steps, solve_time, phase_times = pm.compute_sd_direction(y_pos = init_y_pos, y_neg = init_y_neg, verbose=verbose)
print(descent_direction)
print(np.count_nonzero(np.array(descent_direction)))
test_dir = descent_direction
simplex_iters.append(num_steps)
sub_times['solve'].append(solve_time)
sub_times['phase_times'].append(phase_times)

t3 = time.time()
sub_times['sd'].append(t3 - t2)
    
while abs(steepness) > EPS:
        
    t3 = time.time()
    if reset:
        pm.reset()
        
    # take maximal step
    x_current, alpha, active_inds = P.take_maximal_step(descent_direction, y_pos, y_neg)  
        
    if iteration % 50 == 0 or iteration == 1:
        print('\nIteration {}'.format(iteration))
        print('Objective: {}'.format(obj_value))
        print('Steepness: {}'.format(steepness))
        print('Step length: {}'.format(alpha))
        
    t4 = time.time()
    obj_value = P.c.dot(x_current)
    obj_values.append(obj_value)
    iter_times.append(t4 - t1)
    sub_times['step'].append(t4 - t3) 
    descent_circuits.append(descent_direction)
    step_sizes.append(alpha)     
                
    if math.isinf(alpha):
        # problem is unbounded
        result(status=1, circuits=descent_circuits, steps=step_sizes)
        
    # compute steepest-descent direction
    pm.set_active_inds(active_inds)
    descent_direction, y_pos, y_neg, steepness, num_steps, solve_time, phase_times = pm.compute_sd_direction(
                                                                                                verbose=verbose)
        
    t5 = time.time()
    sub_times['sd'].append(t5 - t4)
    sub_times['solve'].append(solve_time)
    sub_times['phase_times'].append(phase_times)
    simplex_iters.append(num_steps)
        
    iteration += 1
    current_time = t5 - t1
    if current_time > max_time:
        result(status=2)
    if iteration <= save_first_steps:
        np.save('solutions/{}_{}.npy'.format(problem_name, iteration), x_current)

t6 = time.time()
total_time = t6 - t1   
print('Total time for steepest-descent scheme: {}'.format(total_time))

Building polyhedral model. Solve method: dual_simplex
Set parameter Method to value 1
Polyhedral model built!
Polyhedral model build time: 0.006932735443115234
Model is feasible or optimization was successful.
[ 0.          0.         -0.16666667  0.16666667 -0.16666667]
3

Iteration 0
Objective: 25.0
Steepness: -0.16666666666666663
Step length: 30.0
Total time for steepest-descent scheme: 0.009902715682983398


In [16]:
# second_inds = P.get_active_constraints(x_feasible_2)
# print(len(np.intersect1d(init_inds, second_inds)))

In [17]:
# pm.y_neg
# np.count_nonzero(np.array(init_edge))

In [18]:
# Bx= np.dot(B, np.array(x_feasible))
# Bx_edge= np.dot(B,np.array(init_edge))
# Ax= np.dot(A,np.array(init_edge))
# print(Ax)
# print(Bx_edge)

In [19]:
# print(A)
# print(B)
# print(init_edge)

In [20]:
x_new = x_current

In [21]:
x_orig == x_new

array([False, False, False,  True,  True])

In [22]:
diff = x_orig-x_new
print(diff)

[ 5. -5.  5.  0.  0.]


In [23]:
obj_values[-1]

20.0